name: CI

on: [push]

jobs:
  build:

    runs-on: microsoft-windows:10
    strategy:
      matrix:
        python-version: [5.5]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    
